development:
 adapter: postgresql
 encoding: unicode
 database: test_store_development
 pool: 5
 username: postgres
 password: postgres

test:
 adapter: postgresql
 encoding: unicode
 database: test_store_test
 pool: 5
 username: postgres
 password: postgres

 
production:
 adapter: postgresql
 encoding: unicode
 database: test_store_production
 pool: 5
 username: postgres
 password: postgres

